name: Aspect-Based-Sentiment-Analysis
dependencies:
  - python=3.7
  - tensorflow=2.1
  - scikit-learn=0.22
  - pytest=5.3
  - ipython=7.3
  - spacy=2.4
  - pip:
    google-cloud-storage=1.26
    testfixtures=6.14
    transformers=2.5
    optuna=1.3